include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = Parse
Parse_HEADER_FILES = Parse.h PFACL.h PFAnalytics.h PFCloud.h PFCommon.h PFInstallation.h PFObject.h PFQuery.h PFUser.h
Parse_HEADER_FILES_INSTALL_DIR = Parse
Parse_INCLUDE_DIRS = -I../
Parse_OBJC_FILES = Parse.m PFACL.m PFAnalytics.m PFCloud.m PFInstallation.m PFObject.m PFQuery.m PFUser.m
Parse_OBJCFLAGS += -fobjc-arc -fobjc-weak

include $(GNUSTEP_MAKEFILES)/library.make