include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = GLKit
GLKit_HEADER_FILES = GLKit.h GLKMatrix3.h GLKMatrix4.h GLKQuaternion.h GLKVector2.h GLKVector3.h GLKVector4.h
GLKit_HEADER_FILES_INSTALL_DIR = GLKit
GLKit_INCLUDE_DIRS = -I../
GLKit_OBJC_FILES = GLKit.m GLKMatrix4.m GLKQuaternion.m
GLKit_OBJCFLAGS += -fobjc-arc -fobjc-weak

include $(GNUSTEP_MAKEFILES)/library.make