include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = AVFoundation
AVFoundation_HEADER_FILES = AVFoundation.h AVAudioPlayer.h
AVFoundation_HEADER_FILES_INSTALL_DIR = AVFoundation
AVFoundation_INCLUDE_DIRS = -I../
AVFoundation_OBJCC_FILES = AVAudioPlayer.mm
AVFoundation_OBJCCFLAGS += -fobjc-arc -fobjc-weak

include $(GNUSTEP_MAKEFILES)/library.make