include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = BasicExample
BasicExample_OBJC_FILES = main.m AppDelegate.m ViewController.m
BasicExample_TOOL_LIBS += -lAPKit
BasicExample_OBJCFLAGS = -DLINUX

include $(GNUSTEP_MAKEFILES)/tool.make
