include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = UIKit
UIKit_HEADER_FILES = CoreGraphicsExtensions.h NSAttributedString+enumerate.h NSParagraphStyle.h NSValue+NSValueUIGeometryExtensions.h UIApplication.h UIColor.h UIDefines.h UIDevice.h UIEvent.h UIFont.h UIGestureRecognizerSubclass.h UIKit.h UIScreen.h UIViewController.h UIWindow.h
UIKit_HEADER_FILES_INSTALL_DIR = UIKit
UIKit_INCLUDE_DIRS = -I../
UIKit_OBJC_FILES = CoreGraphicsExtensions.m NSAttributedString+enumerate.m NSParagraphStyle.m NSValue+NSValueUIGeometryExtensions.m UIApplication.m UIColor.m UIDevice.m UIEvent.m UIFont.m UIKit.m UIScreen.m UIViewController.m UIWindow.m
UIKit_OBJCFLAGS += -fobjc-arc -fobjc-weak

include $(GNUSTEP_MAKEFILES)/library.make